### ISSUE TITLE
May the sticky tabs be like `resistant` to the close button also?

### ISSUE THREAD

**Issue by evandrocoan** [facelessuser/TabsExtra#42]
Originally posted on: https://github.com/facelessuser/TabsExtra/issues/41#issuecomment-259749885

From this package docs:
>TabsExtra allows users to make a tab sticky. This allows the tab to not close when a bulk close operation is performed. By default, after any close command is run, the sticky tab properties are forgotten. You can make a tab’s stickiness persist by enabling persistent_sticky.

>    // By default TabsExtra forgets a tab's "stickiness" when
    // any "tab close" command is issued.  You can make the tab's
    // "Stickiness" persist by enabling the following feature.
    "persistent_sticky": false,

Firstly, thank you for writhing this package. It is very handy and good to have something link it on Sublime Text.

### Feature suggestion:

Now, may the sticky tabs be like `resistant` to the close button also?

The package https://github.com/DavidGerva/LockTab-Sublime-Plugin does it. It working principle is very simple:

> Right now I just intercept the tab closing, and then I reopen the tab. This is, as far as I know, the only thing I can do. Right now is not possibile avoiding the tab closure!
https://github.com/DavidGerva/LockTab-Sublime-Plugin#todo

Seems pretty good to me. My goal is just to not close the tab. However that package stills not compatible with this built in sticky. As once you trigger the close all command it try also to close the Locked Tab by the other package triggering the pop up window by the package `LockTab`:

![image](https://cloud.githubusercontent.com/assets/5332158/20186798/8e486fd6-a758-11e6-942e-fb5255aa730c.png)

So may suggestion would be to take the `LockTab` package code and integrate with this `persistent_sticky` feature as the `LockTab` package is currently abandoned/unsupported/broke: 

1. https://github.com/DavidGerva/LockTab-Sublime-Plugin/issues/1

So it also will not close the locked/sicked tabs. Now to keep backward compatibility, adding new settings or more kinda integrate the current settings from the package `LockTab` into the current `TabsExtra` settings, extending this package functionality.

**Comment by facelessuser** [comment]
I'm trying to understand.  Basically, you want locked tabs to ask (for each tab) whether you want to close them?

**Comment by evandrocoan** [comment]
Yes, if I mark a tab as locked, I want to be asked whether I want to close them when I hit the close button. 

This would apply to the tabs without any current file changes, as when there are file changes, Sublime Text automatically asks you whether you want to close it saving your changes or if you want to cancel.

**Comment by facelessuser** [comment]
Hmm. I'll have to think about this.  It heads in a direction I don't personally desire, but as it would be optional, I may look into it.

If I do, I won't be utilizing LockTab code as from the description it sounds like it works in a very different undesirable way.

**Comment by Kristinita** [comment]
@facelessuser,

### 1. Closing tabs methods

For close my tabs I use 4 methods:

1. Close only one tab, <kbd>Ctrl+W</kbd>:

```
key evt: control+w
command: intercept_close
plugin rewritten command: tabs_extra_close
```

2. <kbd>Left_Click</kbd> to `tab_close_button` tab element.

3. Close others tabs:

```
key evt: shift+control+f4
command: close_others_by_index
plugin rewritten command: tabs_extra_close
```

4. [**ZenTabs**](https://packagecontrol.io/packages/Zen%20Tabs) tabs closing. That package not ideally, but I don't know better package.

### 2. Requests

1. Not closing tabs if I close my tabs any of 4 methods above. Dialog message like in @evandrocoan request instead of closing.
2. Auto-sticky for unsaved temporary tabs. Because if I close unsaved tab, I lose all my data in tab.
For example, I write GitHub issues and comments use [**GhostText**](https://packagecontrol.io/packages/GhostText) or [**GithubIssue**](https://packagecontrol.io/packages/GitHubIssue) packages. If I close GhostText and GitHubIssue tabs, I lose text written by me in tab.

### 3. Not helped

1. [**Sticky**](https://github.com/avamsi/Sticky) package sticky tabs only if I close it, uses first method.
2. [**LockTab**](https://github.com/DavidGerva/LockTab-Sublime-Plugin) package have many bugs for me.
3. [**LessTabs**](https://github.com/webArtisan/lessTabs) package closing tabs automatically only if I create new file. It is not good behavior.
4. In TidyTabs package [**I have bugs**](https://github.com/bradleyboy/TidyTabs-Sublime/issues).
5. Data from closed GhostText or GitHubIssue unsaved file not saved [**in sublime-session file**](http://ru.stackoverflow.com/a/321754/199934).
6. I don't find packages for [**automatically saving data from unsaved tabs**](https://github.com/jamesfzhang/auto-save/issues/33).


Thanks.

**Comment by facelessuser** [comment]
> <kbd>Left_Click</kbd> to tab_close_button tab element.

As I recall, I don't think I can override the close when pressing the GUI close button.  Sublime run that through a different close path that I can't intercept.

> Auto-sticky for unsaved temporary tabs. Because if I close unsaved tab, I lose all my data in tab.
For example, I write GitHub issues and comments use GhostText or GithubIssue packages. If I close GhostText and GitHubIssue tabs, I lose text written by me in tab.

Unsaved buffers should  be prevented from closing (with a dialog prompt) unless you explicitly choose a close variant that ignores unsaved buffers.  And if you do that...well you picked the command that told you it was going to ignore unsaved buffers.  Is this not what you are seeing?

**Comment by Kristinita** [comment]
@facelessuser ,

> As I recall, I don't think I can override the close when pressing the GUI close button. Sublime run that through a different close path that I can't intercept.

All right, I'll try not to use this method.

> Is this not what you are seeing?

1. I want to keep my data in unsaved buffers if I accidentally close a tab. ZenTabs don't close unsaved buffers, but use methods 1 and 3 I close unsaved buffers without dialog window.
2. For example, I want, that tab with my TODO list — normal file `todo.text`, not unsaved buffer, — always will be open. I spend a time, when I open this file manually after each closing.
	1. ZenTabs close it, if I have many opened tabs,
	2. If I want quickly close unused tabs, I run command `tabs_extra_close` and my `todo.text` tab was closed.
	3. I can accidentally close a tab `todo.text`, run command `tabs_extra_close`.

Thanks.

**Comment by facelessuser** [comment]
I will implement this moving forward.  I have added single close to respect sticky status.  Sadly I still can't intercept the click of the "x" button on a tab, but if you do something like run a command or shortcut to close a single sticky tab, I will prompt.

**Comment by facelessuser** [comment]
Change is here: https://github.com/facelessuser/TabsExtra/commit/7aa3cc93d77ec78cf5cdedc48389b30a7a4814dd.
