### ISSUE TITLE
"fallback_focus" for tab

### ISSUE THREAD

**Issue by mejliu** [facelessuser/TabsExtra#57]
Hi,

Is there a way to add a "fallback_focus"  setting for tab. For example, if the active tab is closed or moved to another view/pane, we can choose which tab should be activated. thanks.

**Comment by facelessuser** [comment]
Sorry for the late response, but there isn't currently a way. Maybe in the future.

**Comment by facelessuser** [comment]
Okay, let me correct my original statement, ` fallback_focus` should apply to when a tab closes, or when a tab is moved from the window. With that said, I did discover an issue that would cause active tabs to not be properly tracked. This has been fixed in #61.

I have no plans to add a separate setting for closing vs a tab getting moved out of a window though. Hopefully if your issue was related to #61, it will be fixed in the next release.

@gir-bot remove P: maybe
